<?php
function record_report_specs(): array
{
    return [

        'journal' => [
            'title'   => 'JOURNAL PUBLICATIONS',
            'columns' => [
                ['S.No', '#'],
                ['Name of the Faculty', 'faculty_name'],
                ['Dept', 'department'],
                ['Author Type', 'author_type'],
                ['Names of Co-Authors at MSEC', 'co_authors'],
                ['Title of the Paper', 'paper_title'],
                ['Journal Name', 'journal_name'],
                ['Journal Type', 'journal_type'],
                ['ISSN Number', 'issn'],
                ['Volume & Issue No', 'volume_issue'],
                ['Month & Year of Publication (mm/yyyy)', 'publication_month'],
                ['Link to the Article / DOI', 'doi'],
                ['Link to Journal Website', 'journal_link'],
                ['Document Link', 'document_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'book' => [
            'title'   => 'BOOK / BOOK CHAPTER PUBLICATIONS',
            'columns' => [
                ['S.No', '#'],
                ['Name of the Faculty', 'faculty_name'],
                ['Dept', 'department'],
                ['Book / Book Chapter', 'publication_category'],
                ['Title of the Book / Book Chapter', 'title'],
                ['Publisher Name', 'publisher_name'],
                ['ISSN / ISBN Number', 'isbn'],
                ['Month & Year of Publication (mm/yyyy)', 'publication_month'],
                ['Document Link', 'document_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'conference' => [
            'title'   => 'CONFERENCE PUBLICATIONS',
            'columns' => [
                ['S.No', '#'],
                ['Name of the Faculty', 'faculty_name'],
                ['Dept', 'department'],
                ['Author Type', 'author_type'],
                ['Title of the Paper', 'paper_title'],
                ['Conference Name', 'conference_name'],
                ['Type', 'conference_type'],
                ['Venue', 'venue'],
                ['Conference Date (dd/mm/yyyy)', 'conference_date'],
                ['Document Link', 'document_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'event' => [
            'title'    => 'LIST OF EVENTS ORGANIZED',
            'subtitle' => '(SEMINAR / WORKSHOP / WEBINAR / FDP / CONFERENCE / SYMPOSIUM)',
            'columns'  => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Date (dd/mm/yyyy)', 'event_date'],
                ['Event Title', 'event_title'],
                ['Event Type', 'event_type'],
                ['Mode', 'mode'],
                ['Chief Guest / Resource Person Name & Designation (with Contact Details)', 'resource_person'],
                ['No. of Participants', 'participants'],
                ['Sponsorship (if any)', 'sponsorship'],
                ['Web Link to Event Report', 'report_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'fdp' => [
            'title'   => 'FACULTY PARTICIPATIONS IN FDP / WORKSHOP / SEMINAR',
            'columns' => [
                ['S.No', '#'],
                ['Name of the Faculty', 'faculty_name'],
                ['Dept', 'department'],
                ['Duration', 'duration'],
                ['Event Type', 'event_type'],
                ['Name of the FDP / Seminar / Workshop', 'title'],
                ['Mode', 'mode'],
                ['Organized By (Name of the Institution / Agency)', 'organized_by'],
                ['Certificate Link', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'mou' => [
            'title'   => 'LIST OF MoUs SIGNED',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Signed Date (dd/mm/yyyy)', 'signed_date'],
                ['Name & Address of the Collaborating Body (Industry / Institution / Agency / etc.,)', 'organization'],
                ['Valid upto (dd/mm/yyyy)', 'valid_upto'],
                ['Purpose of Collaboration', 'purpose'],
                ['Document Link', 'document_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'nptel' => [
            'title'   => 'SWAYAM-NPTEL COURSE COMPLETION',
            'columns' => [
                ['S.No', '#'],
                ['Candidate Name', 'candidate_name'],
                ['Dept', 'department'],
                ['Category', 'category'],
                ['Course Title', 'course_title'],
                ['Session', 'session'],
                ['Grade', 'grade'],
                ['Certificate Link', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'patent' => [
            'title'   => 'PATENTS & COPYRIGHTS',
            'columns' => [
                ['S.No', '#'],
                ['Name of the Faculty', 'faculty_name'],
                ['Dept', 'department'],
                ['Patent / Copyright', 'category'],
                ['Title of the Patent / Copyright', 'title'],
                ['Patent / Copyright Number', 'patent_number'],
                ['Date of Publication (dd/mm/yyyy)', 'publication_date'],
                ['Document Link', 'document_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'internship' => [
            'title'   => 'STUDENTS INTERNSHIP DETAILS',
            'columns' => [
                ['S.No', '#'],
                ['Reg. No', 'reg_no'],
                ['Name of the student', 'student_name'],
                ['Dept / Branch', 'department'],
                ['Title of Internship', 'title'],
                ['Industry/Institution Name & Address', 'industry'],
                ['Duration', 'duration'],
                ['No. of Days', 'days'],
                ['Link to the Certificate / Document', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'placement' => [
            'title'   => 'LIST OF PLACEMENTS',
            'columns' => [
                ['S. No', '#'],
                ['Reg. No', 'reg_no'],
                ['Student Name', 'student_name'],
                ['Dept / Branch', 'department'],
                ['Job Name', 'job_title'],
                ['Mode (On Campus / Off Campus)', 'mode'],
                ['Company Name & Address (with Contact Details)', 'company'],
                ['Pay Scale', 'pay_scale'],
                ['Web Link to Appointment Order', 'appointment_order_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'nss' => [
            'title'   => 'NSS / YRC / RRC PROGRAMMES ORGANIZED',
            'columns' => [
                ['S.No', '#'],
                ['Date (dd/mm/yyyy)', 'activity_date'],
                ['Name of the Activity', 'activity_name'],
                ['Activity Type', 'activity_type'],
                ['Venue', 'venue'],
                ['Name of external Agency / Member involved (Name & Designation with Contact Details)', 'external_agency'],
                ['No. of Student Participated', 'participants'],
                ['Web Link to Event Report', 'report_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'online_course' => [
            'title'   => 'ONLINE COURSES COMPLETED',
            'columns' => [
                ['S.No', '#'],
                ['Candidate Name', 'candidate_name'],
                ['Dept', 'department'],
                ['Category', 'category'],
                ['Course Title', 'course_title'],
                ['Provider', 'provider'],
                ['Duration', 'duration'],
                ['Month & Year', 'month_year'],
                ['Certificate Link', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'student_achievement' => [
            'title'   => 'STUDENTS ACHIEVEMENTS',
            'columns' => [
                ['S.No', '#'],
                ['Reg. No', 'reg_no'],
                ['Name of the student', 'student_name'],
                ['Dept / Branch', 'department'],
                ['Event Type', 'event_type'],
                ['Name of the Event', 'event_name'],
                ['Name of the Function / Programme', 'function_name'],
                ['Date of the event', 'event_date'],
                ['Team / Individual', 'team_individual'],
                ['University / State / National / International', 'level_secured'],
                ['Position secured', 'position_secured'],
                ['Name of the Organising Institution', 'organising_institution'],
                ['Link to the Certificate / Document', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'student_participation' => [
            'title'   => 'STUDENTS PARTICIPATIONS',
            'columns' => [
                ['S.No', '#'],
                ['Reg. No', 'reg_no'],
                ['Name of the student', 'student_name'],
                ['Dept / Branch', 'department'],
                ['Event Type', 'event_type'],
                ['Name of the Event', 'event_name'],
                ['Name of the Function / Programme', 'function_name'],
                ['Date of the event', 'event_date'],
                ['Team / Individual', 'team_individual'],
                ['University / State / National / International', 'level_secured'],
                ['Position secured', 'position_secured'],
                ['Name of the Organising Institution', 'organising_institution'],
                ['Link to the Certificate / Document', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'summer_training' => [
            'title'   => 'STUDENTS TRAINING (SUMMER / WINTER) DETAILS',
            'columns' => [
                ['S.No', '#'],
                ['Reg. No', 'reg_no'],
                ['Name of the student', 'student_name'],
                ['Dept / Branch', 'department'],
                ['Title of Training', 'title'],
                ['Industry/Institution Name & Address', 'industry'],
                ['Duration', 'duration'],
                ['No. of Days', 'days'],
                ['Link to the Certificate / Document', 'certificate_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'value_added' => [
            'title'   => 'LIST OF VALUE ADDED COURSES CONDUCTED',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['From (dd/mm/yyyy)', 'from_date'],
                ['To (dd/mm/yyyy)', 'to_date'],
                ['Course Title', 'course_title'],
                ['Mode', 'mode'],
                ['Resource Person Name & Designation (with Contact Details)', 'resource_person'],
                ['No. of Participants', 'participants'],
                ['Web Link to Event Report', 'report_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'training' => [
            'title'    => 'LIST OF EVENTS ORGANIZED',
            'subtitle' => '(CAREER GUIDANCE / COUNSELLING / ICT / LIFE SKILLS / SOFT SKILLS TRAINING)',
            'columns'  => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Date (dd/mm/yyyy)', 'event_date'],
                ['Event Title', 'event_title'],
                ['Event Type', 'event_type'],
                ['Mode', 'mode'],
                ['Chief Guest / Resource Person Name & Designation (with Contact Details)', 'resource_person'],
                ['No. of Participants', 'participants'],
                ['Sponsorship (if any)', 'sponsorship'],
                ['Web Link to Event Report', 'report_link'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

        'inst_pass_percentage' => [
            'title'   => 'UNIVERSITY PASS PERCENTAGE',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Programme', 'programme'],
                ['Class / Year', 'class_year'],
                ['Semester', 'semester'],
                ['Total Subjects', 'total_subjects'],
                ['Total Students', 'total_students'],
                ['Total Passed', 'total_passed'],
                ['Pass Percentage (%)', 'overall_pass_percentage'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_college_rank' => [
            'title'   => 'RANK IN ANNA UNIVERSITY (COLLEGE)',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Programme', 'programme'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Rank', 'rank_val'],
                ['Rank Type', 'rank_type'],
                ['University', 'university'],
                ['Year / Semester', 'year_semester'],
                ['Achievement Date', 'achievement_date'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_student_rank' => [
            'title'   => 'UNIVERSITY RANK (STUDENTS UNIV. RANKS)',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Programme', 'programme'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['University Rank', 'university_rank'],
                ['Year', 'class_year'],
                ['Semester', 'semester'],
                ['Category', 'category'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_student_cgpa' => [
            'title'   => 'TO IMPROVE II & III YEAR STUDENTS ABOVE 7.5 CGPA',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Programme', 'programme'],
                ['Year', 'class_year'],
                ['Semester', 'semester'],
                ['Reg. No', 'reg_no'],
                ['Student Name', 'student_name'],
                ['CGPA', 'cgpa'],
                ['Eligibility', 'eligibility'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_placement_mnc' => [
            'title'   => 'PLACE 2024-25 BATCH STUDENTS IN TOP MNCS',
            'columns' => [
                ['S.No', '#'],
                ['Batch', 'batch'],
                ['Dept', 'department'],
                ['Reg. No', 'reg_no'],
                ['Student Name', 'student_name'],
                ['Company Name', 'company_name'],
                ['Company Type', 'company_type'],
                ['Placement Status', 'placement_status'],
                ['Package / CTC', 'package_ctc'],
                ['Placement Date', 'placement_date'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_publications' => [
            'title'   => 'QUALITY PUBLICATIONS IN SCOPUS / SCI / SPRINGER / UGC CARE / H-INDEX',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Authors', 'authors'],
                ['Title of Paper', 'title'],
                ['Journal Name', 'journal_name'],
                ['Publication Type', 'publication_type'],
                ['DOI / URL', 'doi_url'],
                ['Publication Date', 'publication_date'],
                ['H-Index', 'h_index'],
                ['Volume / Issue', 'volume_issue'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_books' => [
            'title'   => 'BOOKS PUBLICATION - BOOK',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Book Title', 'book_title'],
                ['Authors', 'authors'],
                ['Publisher', 'publisher'],
                ['ISBN', 'isbn'],
                ['Publication Date', 'publication_date'],
                ['Edition', 'edition'],
                ['URL', 'book_url'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_book_chapters' => [
            'title'   => 'BOOK CHAPTER',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Chapter Title', 'chapter_title'],
                ['Book Title', 'book_title'],
                ['Authors', 'authors'],
                ['Publisher', 'publisher'],
                ['ISBN', 'isbn'],
                ['Chapter Number', 'chapter_number'],
                ['Publication Date', 'publication_date'],
                ['URL', 'chapter_url'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_patents_published' => [
            'title'   => 'PATENT PUBLISHED / DESIGN',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Inventors', 'inventors'],
                ['Title', 'title'],
                ['Patent / Design Number', 'patent_number'],
                ['Type', 'patent_type'],
                ['Application Date', 'application_date'],
                ['Publication Date', 'publication_date'],
                ['Status', 'patent_status'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_patents_granted' => [
            'title'   => 'PATENT GRANTED',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Inventors', 'inventors'],
                ['Title', 'title'],
                ['Patent Number', 'patent_number'],
                ['Grant Date', 'grant_date'],
                ['Granting Authority', 'granting_authority'],
                ['Status', 'patent_status'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_copyrights' => [
            'title'   => 'COPYRIGHTS',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Title / Work', 'title'],
                ['Copyright Number', 'copyright_number'],
                ['Registration Date', 'registration_date'],
                ['Category', 'category'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_sponsored_research' => [
            'title'   => 'SPONSORED RESEARCH (IN LAKHS)',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name / PI', 'faculty_name'],
                ['Dept', 'department'],
                ['Project Title', 'project_title'],
                ['Funding Agency', 'funding_agency'],
                ['Project Amount (in Lakhs)', 'project_amount'],
                ['Start Date', 'start_date'],
                ['End Date', 'end_date'],
                ['Status', 'project_status'],
                ['Project Number', 'project_number'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_consultancy' => [
            'title'   => 'FUNDS CONSULTANCY PROJECTS (IN LAKHS)',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Project Title', 'project_title'],
                ['Client / Organization', 'client_org'],
                ['Project Amount (in Lakhs)', 'project_amount'],
                ['Start Date', 'start_date'],
                ['End Date', 'end_date'],
                ['Status', 'project_status'],
                ['Project Number', 'project_number'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_research_centre' => [
            'title'   => 'RESEARCH CENTRE RECOGNITION FROM ANNA UNIVERSITY',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Recognition Name', 'recognition_name'],
                ['Recognizing Authority', 'recognizing_authority'],
                ['Recognition Date', 'recognition_date'],
                ['Reference Number', 'reference_number'],
                ['Status', 'recognition_status'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_ipr_programmes' => [
            'title'   => 'PROGRAMME ON IPR / HIGHER STUDIES / ENTREPRENEURSHIP',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Programme Type', 'programme_type'],
                ['Programme Title', 'programme_title'],
                ['Date', 'programme_date'],
                ['Organizer', 'organizer'],
                ['Target Audience', 'target_audience'],
                ['Participants', 'participants'],
                ['Description', 'description'],
                ['Outcome', 'outcome'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_faculty_certifications' => [
            'title'   => 'NO. OF ONLINE CERTIFICATION COURSES COMPLETED BY FACULTY',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Course Name', 'course_name'],
                ['Platform / Provider', 'provider'],
                ['Certification Name', 'certification_name'],
                ['Completion Date', 'completion_date'],
                ['Certificate ID', 'certificate_id'],
                ['Status', 'cert_status'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_mou_interactions' => [
            'title'   => 'INDUSTRY INTERACTION / MOU / INDUSTRY SUPPORTED LAB',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Industry Name', 'industry_name'],
                ['Type', 'interaction_type'],
                ['MOU Number', 'mou_number'],
                ['Date', 'interaction_date'],
                ['Validity', 'validity'],
                ['Faculty Coordinator', 'faculty_coordinator'],
                ['Description', 'description'],
                ['Outcome', 'outcome'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_internships' => [
            'title'   => 'STUDENT\'S INDUSTRY INTERNSHIP (4 WEEKS & ABOVE)',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Company / Industry', 'company'],
                ['Start Date', 'start_date'],
                ['End Date', 'end_date'],
                ['Duration (Weeks)', 'duration_weeks'],
                ['Internship Type', 'internship_type'],
                ['Faculty Coordinator', 'faculty_coordinator'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_summer_trainings' => [
            'title'   => 'SUMMER TRAINING (LESS THAN 4 WEEKS)',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Organization', 'organization'],
                ['Start Date', 'start_date'],
                ['End Date', 'end_date'],
                ['Duration (Days)', 'duration_days'],
                ['Training Title', 'training_title'],
                ['Faculty Coordinator', 'faculty_coordinator'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_student_projects' => [
            'title'   => 'QUALITY STUDENTS PROJECT AND PUBLISH IN YOUTUBE',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Project Title', 'project_title'],
                ['Project Guide', 'project_guide'],
                ['Category', 'project_category'],
                ['YouTube URL', 'youtube_url'],
                ['Publication Date', 'publication_date'],
                ['Views', 'views_count'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_faculty_participations' => [
            'title'   => 'FACULTY PARTICIPATIONS IN FDP / TRAINING / STTP / CONFERENCE',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Programme Type', 'programme_type'],
                ['Programme Title', 'programme_title'],
                ['Organizer', 'organizer'],
                ['Location / Mode', 'location_mode'],
                ['Start Date', 'start_date'],
                ['End Date', 'end_date'],
                ['Duration', 'duration'],
                ['Certificate Number', 'certificate_number'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_society_memberships' => [
            'title'   => 'MEMBERSHIP IN PROFESSIONAL SOCIETIES',
            'columns' => [
                ['S.No', '#'],
                ['Faculty Name', 'faculty_name'],
                ['Dept', 'department'],
                ['Society Name', 'society_name'],
                ['Membership Number', 'membership_number'],
                ['Membership Type', 'membership_type'],
                ['Start Date', 'start_date'],
                ['Expiry Date', 'expiry_date'],
                ['Status', 'membership_status'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_newsletters' => [
            'title'   => 'NEWSLETTER',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Newsletter Title', 'newsletter_title'],
                ['Volume', 'volume'],
                ['Issue', 'issue'],
                ['Publication Date', 'publication_date'],
                ['Editor / Coordinator', 'editor_coordinator'],
                ['Description', 'description'],
                ['URL', 'newsletter_url'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_student_certifications' => [
            'title'   => 'STUDENT ONLINE CERTIFICATION',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Course Name', 'course_name'],
                ['Platform', 'platform'],
                ['Certification Name', 'certification_name'],
                ['Completion Date', 'completion_date'],
                ['Certificate ID', 'certificate_id'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_nss_events' => [
            'title'   => 'NO OF EVENTS CONDUCTED BY NSS',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Event Name', 'event_name'],
                ['Date', 'event_date'],
                ['Venue', 'venue'],
                ['NSS Unit', 'nss_unit'],
                ['Coordinator', 'coordinator'],
                ['Participants', 'participants'],
                ['Description', 'description'],
                ['Outcome', 'outcome'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_inter_inst_within' => [
            'title'   => 'PARTICIPATION IN INTER-INSTITUTE EVENTS WITHIN STATE',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Event Name', 'event_name'],
                ['Host Institution', 'host_institution'],
                ['Location', 'location'],
                ['Date', 'event_date'],
                ['Participation Type', 'participation_type'],
                ['Position / Award', 'position_award'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_inter_inst_outside' => [
            'title'   => 'PARTICIPATION IN INTER-INSTITUTE EVENTS OUTSIDE STATE',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Event Name', 'event_name'],
                ['Host Institution', 'host_institution'],
                ['State', 'state_name'],
                ['City', 'city'],
                ['Location', 'location'],
                ['Date', 'event_date'],
                ['Participation Type', 'participation_type'],
                ['Position / Award', 'position_award'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_inter_inst_awards' => [
            'title'   => 'AWARDS/MEDALS IN INTER-INSTITUTE EVENTS BY STUDENTS',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Event Name', 'event_name'],
                ['Host Institution', 'host_institution'],
                ['State', 'state_name'],
                ['Location', 'location'],
                ['Award / Medal', 'award_medal'],
                ['Position', 'position_secured'],
                ['Date', 'event_date'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_value_added_courses' => [
            'title'   => 'NO OF VALUE ADDED / HANDS ON TRAINING COURSES',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Course Name', 'course_name'],
                ['Course Type', 'course_type'],
                ['Organizer', 'organizer'],
                ['Start Date', 'start_date'],
                ['End Date', 'end_date'],
                ['Duration', 'duration'],
                ['Participants', 'participants'],
                ['Faculty Coordinator', 'faculty_coordinator'],
                ['Description', 'description'],
                ['Outcome', 'outcome'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_sports_state' => [
            'title'   => 'EVENT PARTICIPATION IN SPORTS - STATE LEVEL',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Sport', 'sport'],
                ['Event Name', 'event_name'],
                ['Level', 'level_secured'],
                ['Date', 'event_date'],
                ['Venue', 'venue'],
                ['Position', 'participation_position'],
                ['Award', 'award'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_sports_national' => [
            'title'   => 'EVENT PARTICIPATION IN SPORTS - NATIONAL LEVEL',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Sport', 'sport'],
                ['Event Name', 'event_name'],
                ['Level', 'level_secured'],
                ['Date', 'event_date'],
                ['Venue', 'venue'],
                ['Position', 'participation_position'],
                ['Award', 'award'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_innovation_events' => [
            'title'   => 'INNOVATION EVENTS NEED TO CONDUCT IN EVERY DEPARTMENT',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Event Name', 'event_name'],
                ['Event Type', 'event_type'],
                ['Date', 'event_date'],
                ['Coordinator', 'coordinator'],
                ['Participants', 'participants'],
                ['Outcome', 'outcome'],
                ['Theme', 'innovation_theme'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_iic_activities' => [
            'title'   => 'IIC ACTIVITIES',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Activity Name', 'activity_name'],
                ['Activity Type', 'activity_type'],
                ['Date', 'activity_date'],
                ['Organizer', 'organizer'],
                ['Coordinator', 'coordinator'],
                ['Participants', 'participants'],
                ['Outcome', 'outcome'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_website_updations' => [
            'title'   => 'WEBSITE UPDATION',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Update Title', 'update_title'],
                ['Page / Section', 'page_section'],
                ['Updated By', 'updated_by'],
                ['Update Date', 'update_date'],
                ['Description', 'description'],
                ['URL', 'site_url'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_google_ratings' => [
            'title'   => 'GOOGLE RATING',
            'columns' => [
                ['S.No', '#'],
                ['Dept / Institution', 'department'],
                ['Google Rating', 'google_rating'],
                ['Review Count', 'review_count'],
                ['Measurement Date', 'measurement_date'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_startups' => [
            'title'   => 'START UP',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Startup Name', 'startup_name'],
                ['Founders', 'founders'],
                ['Founder Type', 'founder_type'],
                ['Reg. No', 'reg_no'],
                ['Startup Type', 'startup_type'],
                ['Registration Number', 'registration_number'],
                ['Registration Date', 'registration_date'],
                ['Status', 'startup_status'],
                ['Description', 'description'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_alumni_chapters' => [
            'title'   => 'ALUMNI CHAPTER',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Chapter Name', 'chapter_name'],
                ['Location', 'location'],
                ['Coordinator', 'coordinator'],
                ['Formation Date', 'formation_date'],
                ['Member Count', 'member_count'],
                ['Activities', 'activities'],
                ['Status', 'chapter_status'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_awards_recognitions' => [
            'title'   => 'AWARDS & RECOGNITION (DEPT / FACULTY)',
            'columns' => [
                ['S.No', '#'],
                ['Dept', 'department'],
                ['Faculty Name', 'faculty_name'],
                ['Person Name', 'person_name'],
                ['Recognition Type', 'recognition_type'],
                ['Organization', 'organization'],
                ['Title / Award', 'title_award'],
                ['Date', 'achievement_date'],
                ['Role / Responsibility', 'role_responsibility'],
                ['Reference Number', 'reference_number'],
                ['Remarks', 'remarks'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],
        'inst_spoken_tutorials' => [
            'title'   => 'NO. OF STUDENTS COMPLETED IIT-BOMBAY SPOKEN TUTORIAL COURSES',
            'columns' => [
                ['S.No', '#'],
                ['Student Name', 'student_name'],
                ['Reg. No', 'reg_no'],
                ['Dept', 'department'],
                ['Course Name', 'course_name'],
                ['Tutorial Name', 'tutorial_name'],
                ['Completion Date', 'completion_date'],
                ['Certificate ID', 'certificate_id'],
                ['Platform', 'platform'],
                ['Proof Attachment', 'proof_file'],
            ],
        ],

    ];
}

function record_report_spec(string $type): ?array
{
    return record_report_specs()[$type] ?? null;
}
