-- ===========================================================================
--  Institutional & Department Achievement Upload Tables (39 Categories)
--  Fully normalized, strongly typed schema following the existing ATTS
--  table design with standard workflow columns, foreign keys, and indexes.
--  Idempotent (CREATE TABLE IF NOT EXISTS).
-- ===========================================================================
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. UNIVERSITY PASS PERCENTAGE (Parent submission)
CREATE TABLE IF NOT EXISTS inst_pass_percentage (
  id                      INT AUTO_INCREMENT PRIMARY KEY,
  academic_year           VARCHAR(20)  NOT NULL,
  department              VARCHAR(150) NOT NULL,
  programme               VARCHAR(150) NOT NULL,
  class_year              VARCHAR(50)  NOT NULL,
  semester                VARCHAR(50)  NOT NULL,
  exam_session            VARCHAR(50)  NULL,
  total_subjects          INT          NOT NULL DEFAULT 0,
  total_students          INT          NOT NULL DEFAULT 0,
  total_passed            INT          NOT NULL DEFAULT 0,
  overall_pass_percentage DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  proof_file              VARCHAR(255) NULL,
  status                  ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark           VARCHAR(500) NULL,
  created_by              INT          NULL,
  approved_by             INT          NULL,
  created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ipp_dept (department),
  KEY idx_ipp_status (status),
  KEY idx_ipp_year (academic_year),
  KEY idx_ipp_created (created_by),
  CONSTRAINT fk_ipp_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ipp_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 1b. UNIVERSITY PASS PERCENTAGE (Child rows for subject-wise & student details)
CREATE TABLE IF NOT EXISTS inst_pass_percentage_rows (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  pass_percentage_id INT          NOT NULL,
  class_year         VARCHAR(50)  NULL,
  semester           VARCHAR(50)  NULL,
  subject_code       VARCHAR(50)  NOT NULL,
  subject_name       VARCHAR(255) NOT NULL,
  reg_no             VARCHAR(50)  NULL,
  student_name       VARCHAR(190) NULL,
  pass_status        VARCHAR(20)  NOT NULL DEFAULT 'Pass',
  total_members      INT          NOT NULL DEFAULT 0,
  passed_members     INT          NOT NULL DEFAULT 0,
  pass_percentage    DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  sort_order         INT          NOT NULL DEFAULT 0,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_ippr_parent (pass_percentage_id),
  CONSTRAINT fk_ippr_parent FOREIGN KEY (pass_percentage_id) REFERENCES inst_pass_percentage(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. RANK IN ANNA UNIVERSITY (College)
CREATE TABLE IF NOT EXISTS inst_college_rank (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  programme        VARCHAR(150) NULL,
  student_name     VARCHAR(190) NULL,
  reg_no           VARCHAR(50)  NULL,
  rank_val         VARCHAR(50)  NOT NULL,
  rank_type        VARCHAR(100) NULL,
  university       VARCHAR(190) NOT NULL DEFAULT 'Anna University',
  year_semester    VARCHAR(50)  NULL,
  achievement_date VARCHAR(50)  NULL,
  remarks          TEXT         NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_icr_dept (department),
  KEY idx_icr_status (status),
  KEY idx_icr_year (academic_year),
  KEY idx_icr_created (created_by),
  CONSTRAINT fk_icr_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_icr_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. UNIVERSITY RANK (Students Univ. Ranks)
CREATE TABLE IF NOT EXISTS inst_student_rank (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  academic_year   VARCHAR(20)  NOT NULL,
  department      VARCHAR(150) NOT NULL,
  exam_session    VARCHAR(50)  NULL,
  programme       VARCHAR(150) NULL,
  student_name    VARCHAR(190) NOT NULL,
  reg_no          VARCHAR(50)  NOT NULL,
  university_rank VARCHAR(50)  NOT NULL,
  class_year      VARCHAR(50)  NULL,
  semester        VARCHAR(50)  NULL,
  category        VARCHAR(100) NULL,
  remarks         TEXT         NULL,
  proof_file      VARCHAR(255) NULL,
  status          ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark   VARCHAR(500) NULL,
  created_by      INT          NULL,
  approved_by     INT          NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_isr_dept (department),
  KEY idx_isr_status (status),
  KEY idx_isr_year (academic_year),
  KEY idx_isr_created (created_by),
  CONSTRAINT fk_isr_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_isr_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. TO IMPROVE II & III YEAR STUDENTS ABOVE 7.5 CGPA
CREATE TABLE IF NOT EXISTS inst_student_cgpa (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  academic_year VARCHAR(20)  NOT NULL,
  department    VARCHAR(150) NOT NULL,
  exam_session  VARCHAR(50)  NULL,
  programme     VARCHAR(150) NULL,
  class_year    VARCHAR(50)  NOT NULL,
  semester      VARCHAR(50)  NOT NULL,
  reg_no        VARCHAR(50)  NOT NULL,
  student_name  VARCHAR(190) NOT NULL,
  cgpa          DECIMAL(4,2) NOT NULL,
  eligibility   VARCHAR(50)  NOT NULL DEFAULT 'Eligible (Above 7.5)',
  remarks       TEXT         NULL,
  proof_file    VARCHAR(255) NULL,
  status        ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark VARCHAR(500) NULL,
  created_by    INT          NULL,
  approved_by   INT          NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_isc_dept (department),
  KEY idx_isc_status (status),
  KEY idx_isc_year (academic_year),
  KEY idx_isc_created (created_by),
  CONSTRAINT fk_isc_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_isc_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. PLACE 2024-25 BATCH STUDENTS IN TOP MNCs
CREATE TABLE IF NOT EXISTS inst_placement_mnc (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  batch            VARCHAR(50)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  reg_no           VARCHAR(50)  NOT NULL,
  student_name     VARCHAR(190) NOT NULL,
  company_name     VARCHAR(255) NOT NULL,
  company_type     VARCHAR(100) NULL,
  placement_status VARCHAR(100) NOT NULL DEFAULT 'Placed',
  package_ctc      VARCHAR(100) NULL,
  placement_date   VARCHAR(50)  NULL,
  remarks          TEXT         NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ipm_dept (department),
  KEY idx_ipm_status (status),
  KEY idx_ipm_year (academic_year),
  KEY idx_ipm_created (created_by),
  CONSTRAINT fk_ipm_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ipm_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. QUALITY PUBLICATIONS IN SCOPUS / SCI / SPRINGER / UGC CARE / H-INDEX
CREATE TABLE IF NOT EXISTS inst_publications (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  faculty_name     VARCHAR(190) NOT NULL,
  authors          TEXT         NOT NULL,
  title            TEXT         NOT NULL,
  journal_name     VARCHAR(255) NOT NULL,
  publication_type VARCHAR(100) NOT NULL,
  doi_url          VARCHAR(500) NULL,
  publication_date VARCHAR(50)  NULL,
  h_index          VARCHAR(50)  NULL,
  volume_issue     VARCHAR(100) NULL,
  remarks          TEXT         NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ipub_dept (department),
  KEY idx_ipub_status (status),
  KEY idx_ipub_year (academic_year),
  KEY idx_ipub_created (created_by),
  CONSTRAINT fk_ipub_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ipub_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. BOOKS PUBLICATION - BOOK
CREATE TABLE IF NOT EXISTS inst_books (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  faculty_name     VARCHAR(190) NOT NULL,
  book_title       TEXT         NOT NULL,
  authors          TEXT         NOT NULL,
  publisher        VARCHAR(255) NOT NULL,
  isbn             VARCHAR(100) NOT NULL,
  publication_date VARCHAR(50)  NULL,
  edition          VARCHAR(100) NULL,
  book_url         VARCHAR(500) NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ibk_dept (department),
  KEY idx_ibk_status (status),
  KEY idx_ibk_year (academic_year),
  KEY idx_ibk_created (created_by),
  CONSTRAINT fk_ibk_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ibk_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. BOOK CHAPTER
CREATE TABLE IF NOT EXISTS inst_book_chapters (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  faculty_name     VARCHAR(190) NOT NULL,
  chapter_title    TEXT         NOT NULL,
  book_title       TEXT         NOT NULL,
  authors          TEXT         NOT NULL,
  publisher        VARCHAR(255) NOT NULL,
  isbn             VARCHAR(100) NOT NULL,
  chapter_number   VARCHAR(50)  NULL,
  publication_date VARCHAR(50)  NULL,
  chapter_url      VARCHAR(500) NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ibc_dept (department),
  KEY idx_ibc_status (status),
  KEY idx_ibc_year (academic_year),
  KEY idx_ibc_created (created_by),
  CONSTRAINT fk_ibc_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ibc_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. PATENT PUBLISHED / DESIGN
CREATE TABLE IF NOT EXISTS inst_patents_published (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  faculty_name     VARCHAR(190) NOT NULL,
  inventors        TEXT         NOT NULL,
  title            TEXT         NOT NULL,
  patent_number    VARCHAR(100) NOT NULL,
  patent_type      VARCHAR(100) NOT NULL DEFAULT 'Patent',
  application_date VARCHAR(50)  NULL,
  publication_date VARCHAR(50)  NULL,
  patent_status    VARCHAR(100) NULL,
  remarks          TEXT         NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ippb_dept (department),
  KEY idx_ippb_status (status),
  KEY idx_ippb_year (academic_year),
  KEY idx_ippb_created (created_by),
  CONSTRAINT fk_ippb_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ippb_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. PATENT GRANTED
CREATE TABLE IF NOT EXISTS inst_patents_granted (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  faculty_name       VARCHAR(190) NOT NULL,
  inventors          TEXT         NOT NULL,
  title              TEXT         NOT NULL,
  patent_number      VARCHAR(100) NOT NULL,
  grant_date         VARCHAR(50)  NOT NULL,
  granting_authority VARCHAR(255) NOT NULL,
  patent_status      VARCHAR(100) NULL,
  remarks            TEXT         NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ipgr_dept (department),
  KEY idx_ipgr_status (status),
  KEY idx_ipgr_year (academic_year),
  KEY idx_ipgr_created (created_by),
  CONSTRAINT fk_ipgr_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ipgr_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. COPYRIGHTS
CREATE TABLE IF NOT EXISTS inst_copyrights (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  academic_year     VARCHAR(20)  NOT NULL,
  department        VARCHAR(150) NOT NULL,
  exam_session      VARCHAR(50)  NULL,
  faculty_name      VARCHAR(190) NOT NULL,
  title             TEXT         NOT NULL,
  copyright_number  VARCHAR(100) NOT NULL,
  registration_date VARCHAR(50)  NOT NULL,
  category          VARCHAR(100) NULL,
  remarks           TEXT         NULL,
  proof_file        VARCHAR(255) NULL,
  status            ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark     VARCHAR(500) NULL,
  created_by        INT          NULL,
  approved_by       INT          NULL,
  created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_icpr_dept (department),
  KEY idx_icpr_status (status),
  KEY idx_icpr_year (academic_year),
  KEY idx_icpr_created (created_by),
  CONSTRAINT fk_icpr_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_icpr_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. SPONSORED RESEARCH (in Lakhs)
CREATE TABLE IF NOT EXISTS inst_sponsored_research (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  academic_year  VARCHAR(20)   NOT NULL,
  department     VARCHAR(150)  NOT NULL,
  exam_session   VARCHAR(50)   NULL,
  faculty_name   VARCHAR(190)  NOT NULL,
  project_title  TEXT          NOT NULL,
  funding_agency VARCHAR(255)  NOT NULL,
  project_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  start_date     VARCHAR(50)   NULL,
  end_date       VARCHAR(50)   NULL,
  project_status VARCHAR(100)  NULL,
  project_number VARCHAR(100)  NULL,
  proof_file     VARCHAR(255)  NULL,
  status         ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark  VARCHAR(500)  NULL,
  created_by     INT           NULL,
  approved_by    INT           NULL,
  created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_isrch_dept (department),
  KEY idx_isrch_status (status),
  KEY idx_isrch_year (academic_year),
  KEY idx_isrch_created (created_by),
  CONSTRAINT fk_isrch_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_isrch_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. FUNDS CONSULTANCY PROJECTS (in Lakhs)
CREATE TABLE IF NOT EXISTS inst_consultancy (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  academic_year  VARCHAR(20)   NOT NULL,
  department     VARCHAR(150)  NOT NULL,
  exam_session   VARCHAR(50)   NULL,
  faculty_name   VARCHAR(190)  NOT NULL,
  project_title  TEXT          NOT NULL,
  client_org     VARCHAR(255)  NOT NULL,
  project_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  start_date     VARCHAR(50)   NULL,
  end_date       VARCHAR(50)   NULL,
  project_status VARCHAR(100)  NULL,
  project_number VARCHAR(100)  NULL,
  proof_file     VARCHAR(255)  NULL,
  status         ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark  VARCHAR(500)  NULL,
  created_by     INT           NULL,
  approved_by    INT           NULL,
  created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_icons_dept (department),
  KEY idx_icons_status (status),
  KEY idx_icons_year (academic_year),
  KEY idx_icons_created (created_by),
  CONSTRAINT fk_icons_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_icons_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. RESEARCH CENTRE RECOGNITION FROM ANNA UNIVERSITY
CREATE TABLE IF NOT EXISTS inst_research_centre (
  id                   INT AUTO_INCREMENT PRIMARY KEY,
  academic_year        VARCHAR(20)  NOT NULL,
  department           VARCHAR(150) NOT NULL,
  exam_session         VARCHAR(50)  NULL,
  recognition_name     VARCHAR(255) NOT NULL,
  recognizing_authority VARCHAR(255) NOT NULL DEFAULT 'Anna University',
  recognition_date     VARCHAR(50)  NULL,
  reference_number     VARCHAR(100) NULL,
  recognition_status   VARCHAR(100) NULL,
  remarks              TEXT         NULL,
  proof_file           VARCHAR(255) NULL,
  status               ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark        VARCHAR(500) NULL,
  created_by           INT          NULL,
  approved_by          INT          NULL,
  created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_irc_dept (department),
  KEY idx_irc_status (status),
  KEY idx_irc_year (academic_year),
  KEY idx_irc_created (created_by),
  CONSTRAINT fk_irc_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_irc_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 15. PROGRAMME ON IPR / HIGHER STUDIES / ENTREPRENEURSHIP
CREATE TABLE IF NOT EXISTS inst_ipr_programmes (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  academic_year   VARCHAR(20)  NOT NULL,
  department      VARCHAR(150) NOT NULL,
  exam_session    VARCHAR(50)  NULL,
  programme_type  VARCHAR(100) NOT NULL,
  programme_title TEXT         NOT NULL,
  programme_date  VARCHAR(50)  NOT NULL,
  organizer       VARCHAR(255) NOT NULL,
  target_audience VARCHAR(190) NULL,
  participants    INT          NOT NULL DEFAULT 0,
  description     TEXT         NULL,
  outcome         TEXT         NULL,
  proof_file      VARCHAR(255) NULL,
  status          ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark   VARCHAR(500) NULL,
  created_by      INT          NULL,
  approved_by     INT          NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iipr_dept (department),
  KEY idx_iipr_status (status),
  KEY idx_iipr_year (academic_year),
  KEY idx_iipr_created (created_by),
  CONSTRAINT fk_iipr_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iipr_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 16. NO. OF ONLINE CERTIFICATION COURSES COMPLETED BY FACULTY
CREATE TABLE IF NOT EXISTS inst_faculty_certifications (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  faculty_name       VARCHAR(190) NOT NULL,
  course_name        TEXT         NOT NULL,
  provider           VARCHAR(190) NOT NULL,
  certification_name VARCHAR(255) NULL,
  completion_date    VARCHAR(50)  NOT NULL,
  certificate_id     VARCHAR(100) NULL,
  cert_status        VARCHAR(100) NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ifc_dept (department),
  KEY idx_ifc_status (status),
  KEY idx_ifc_year (academic_year),
  KEY idx_ifc_created (created_by),
  CONSTRAINT fk_ifc_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ifc_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 17. INDUSTRY INTERACTION / MOU / INDUSTRY SUPPORTED LAB
CREATE TABLE IF NOT EXISTS inst_mou_interactions (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  academic_year       VARCHAR(20)  NOT NULL,
  department          VARCHAR(150) NOT NULL,
  exam_session        VARCHAR(50)  NULL,
  industry_name       VARCHAR(255) NOT NULL,
  interaction_type    VARCHAR(100) NOT NULL,
  mou_number          VARCHAR(100) NULL,
  interaction_date    VARCHAR(50)  NOT NULL,
  validity            VARCHAR(100) NULL,
  faculty_coordinator VARCHAR(190) NULL,
  description         TEXT         NULL,
  outcome             TEXT         NULL,
  proof_file          VARCHAR(255) NULL,
  status              ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark       VARCHAR(500) NULL,
  created_by          INT          NULL,
  approved_by         INT          NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_imi_dept (department),
  KEY idx_imi_status (status),
  KEY idx_imi_year (academic_year),
  KEY idx_imi_created (created_by),
  CONSTRAINT fk_imi_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_imi_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 18. STUDENT'S INDUSTRY INTERNSHIP (4 weeks & above)
CREATE TABLE IF NOT EXISTS inst_internships (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  academic_year       VARCHAR(20)  NOT NULL,
  department          VARCHAR(150) NOT NULL,
  exam_session        VARCHAR(50)  NULL,
  student_name        VARCHAR(190) NOT NULL,
  reg_no              VARCHAR(50)  NOT NULL,
  company             VARCHAR(255) NOT NULL,
  start_date          VARCHAR(50)  NOT NULL,
  end_date            VARCHAR(50)  NOT NULL,
  duration_weeks      DECIMAL(5,1) NOT NULL,
  internship_type     VARCHAR(100) NULL,
  faculty_coordinator VARCHAR(190) NULL,
  certificate_id      VARCHAR(100) NULL,
  proof_file          VARCHAR(255) NULL,
  status              ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark       VARCHAR(500) NULL,
  created_by          INT          NULL,
  approved_by         INT          NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iint_dept (department),
  KEY idx_iint_status (status),
  KEY idx_iint_year (academic_year),
  KEY idx_iint_created (created_by),
  CONSTRAINT fk_iint_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iint_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 19. SUMMER TRAINING (less than 4 weeks)
CREATE TABLE IF NOT EXISTS inst_summer_trainings (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  academic_year       VARCHAR(20)  NOT NULL,
  department          VARCHAR(150) NOT NULL,
  exam_session        VARCHAR(50)  NULL,
  student_name        VARCHAR(190) NOT NULL,
  reg_no              VARCHAR(50)  NOT NULL,
  organization        VARCHAR(255) NOT NULL,
  start_date          VARCHAR(50)  NOT NULL,
  end_date            VARCHAR(50)  NOT NULL,
  duration_days       VARCHAR(50)  NOT NULL,
  training_title      TEXT         NOT NULL,
  faculty_coordinator VARCHAR(190) NULL,
  certificate_id      VARCHAR(100) NULL,
  proof_file          VARCHAR(255) NULL,
  status              ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark       VARCHAR(500) NULL,
  created_by          INT          NULL,
  approved_by         INT          NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ist_dept (department),
  KEY idx_ist_status (status),
  KEY idx_ist_year (academic_year),
  KEY idx_ist_created (created_by),
  CONSTRAINT fk_ist_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ist_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 20. QUALITY STUDENTS PROJECT AND PUBLISH THE PROJECTS IN YOUTUBE
CREATE TABLE IF NOT EXISTS inst_student_projects (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  student_name     VARCHAR(190) NOT NULL,
  reg_no           VARCHAR(50)  NOT NULL,
  project_title    TEXT         NOT NULL,
  project_guide    VARCHAR(190) NOT NULL,
  project_category VARCHAR(100) NULL,
  youtube_url      VARCHAR(500) NOT NULL,
  publication_date VARCHAR(50)  NULL,
  views_count      VARCHAR(50)  NULL,
  remarks          TEXT         NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_isp_dept (department),
  KEY idx_isp_status (status),
  KEY idx_isp_year (academic_year),
  KEY idx_isp_created (created_by),
  CONSTRAINT fk_isp_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_isp_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 21. FACULTY PARTICIPATIONS IN FDP / TRAINING / STTP / CONFERENCE
CREATE TABLE IF NOT EXISTS inst_faculty_participations (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  faculty_name       VARCHAR(190) NOT NULL,
  programme_type     VARCHAR(100) NOT NULL,
  programme_title    TEXT         NOT NULL,
  organizer          VARCHAR(255) NOT NULL,
  location_mode      VARCHAR(100) NULL,
  start_date         VARCHAR(50)  NOT NULL,
  end_date           VARCHAR(50)  NOT NULL,
  duration           VARCHAR(100) NULL,
  certificate_number VARCHAR(100) NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ifp_dept (department),
  KEY idx_ifp_status (status),
  KEY idx_ifp_year (academic_year),
  KEY idx_ifp_created (created_by),
  CONSTRAINT fk_ifp_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ifp_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 22. MEMBERSHIP IN PROFESSIONAL SOCIETIES
CREATE TABLE IF NOT EXISTS inst_society_memberships (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  academic_year     VARCHAR(20)  NOT NULL,
  department        VARCHAR(150) NOT NULL,
  exam_session      VARCHAR(50)  NULL,
  faculty_name      VARCHAR(190) NOT NULL,
  society_name      VARCHAR(255) NOT NULL,
  membership_number VARCHAR(100) NOT NULL,
  membership_type   VARCHAR(100) NULL,
  start_date        VARCHAR(50)  NULL,
  expiry_date       VARCHAR(50)  NULL,
  membership_status VARCHAR(100) NULL,
  proof_file        VARCHAR(255) NULL,
  status            ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark     VARCHAR(500) NULL,
  created_by        INT          NULL,
  approved_by       INT          NULL,
  created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ism_dept (department),
  KEY idx_ism_status (status),
  KEY idx_ism_year (academic_year),
  KEY idx_ism_created (created_by),
  CONSTRAINT fk_ism_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ism_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 23. NEWSLETTER
CREATE TABLE IF NOT EXISTS inst_newsletters (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  newsletter_title   VARCHAR(255) NOT NULL,
  volume             VARCHAR(50)  NULL,
  issue              VARCHAR(50)  NULL,
  publication_date   VARCHAR(50)  NULL,
  editor_coordinator VARCHAR(190) NOT NULL,
  description        TEXT         NULL,
  newsletter_url     VARCHAR(500) NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_inews_dept (department),
  KEY idx_inews_status (status),
  KEY idx_inews_year (academic_year),
  KEY idx_inews_created (created_by),
  CONSTRAINT fk_inews_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_inews_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 24. STUDENT ONLINE CERTIFICATION
CREATE TABLE IF NOT EXISTS inst_student_certifications (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  student_name       VARCHAR(190) NOT NULL,
  reg_no             VARCHAR(50)  NOT NULL,
  course_name        TEXT         NOT NULL,
  platform           VARCHAR(190) NOT NULL,
  certification_name VARCHAR(255) NULL,
  completion_date    VARCHAR(50)  NOT NULL,
  certificate_id     VARCHAR(100) NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iscert_dept (department),
  KEY idx_iscert_status (status),
  KEY idx_iscert_year (academic_year),
  KEY idx_iscert_created (created_by),
  CONSTRAINT fk_iscert_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iscert_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 25. NO OF EVENTS CONDUCTED BY NSS
CREATE TABLE IF NOT EXISTS inst_nss_events (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  academic_year VARCHAR(20)  NOT NULL,
  department    VARCHAR(150) NOT NULL,
  exam_session  VARCHAR(50)  NULL,
  event_name    TEXT         NOT NULL,
  event_date    VARCHAR(50)  NOT NULL,
  venue         VARCHAR(255) NOT NULL,
  nss_unit      VARCHAR(100) NULL,
  coordinator   VARCHAR(190) NOT NULL,
  participants  INT          NOT NULL DEFAULT 0,
  description   TEXT         NULL,
  outcome       TEXT         NULL,
  proof_file    VARCHAR(255) NULL,
  status        ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark VARCHAR(500) NULL,
  created_by    INT          NULL,
  approved_by   INT          NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_inss_dept (department),
  KEY idx_inss_status (status),
  KEY idx_inss_year (academic_year),
  KEY idx_inss_created (created_by),
  CONSTRAINT fk_inss_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_inss_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 26. PARTICIPATION IN INTER-INSTITUTE EVENTS BY STUDENTS WITHIN STATE
CREATE TABLE IF NOT EXISTS inst_inter_inst_within (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  student_name       VARCHAR(190) NOT NULL,
  reg_no             VARCHAR(50)  NOT NULL,
  event_name         TEXT         NOT NULL,
  host_institution   VARCHAR(255) NOT NULL,
  location           VARCHAR(190) NOT NULL,
  event_date         VARCHAR(50)  NOT NULL,
  participation_type VARCHAR(100) NULL,
  position_award     VARCHAR(190) NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iiw_dept (department),
  KEY idx_iiw_status (status),
  KEY idx_iiw_year (academic_year),
  KEY idx_iiw_created (created_by),
  CONSTRAINT fk_iiw_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iiw_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 27. PARTICIPATION IN INTER-INSTITUTE EVENTS BY STUDENTS OUTSIDE STATE
CREATE TABLE IF NOT EXISTS inst_inter_inst_outside (
  id                 INT AUTO_INCREMENT PRIMARY KEY,
  academic_year      VARCHAR(20)  NOT NULL,
  department         VARCHAR(150) NOT NULL,
  exam_session       VARCHAR(50)  NULL,
  student_name       VARCHAR(190) NOT NULL,
  reg_no             VARCHAR(50)  NOT NULL,
  event_name         TEXT         NOT NULL,
  host_institution   VARCHAR(255) NOT NULL,
  state_name         VARCHAR(100) NOT NULL,
  city               VARCHAR(100) NOT NULL,
  location           VARCHAR(190) NULL,
  event_date         VARCHAR(50)  NOT NULL,
  participation_type VARCHAR(100) NULL,
  position_award     VARCHAR(190) NULL,
  proof_file         VARCHAR(255) NULL,
  status             ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark      VARCHAR(500) NULL,
  created_by         INT          NULL,
  approved_by        INT          NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iio_dept (department),
  KEY idx_iio_status (status),
  KEY idx_iio_year (academic_year),
  KEY idx_iio_created (created_by),
  CONSTRAINT fk_iio_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iio_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 28. AWARDS/MEDALS IN INTER-INSTITUTE EVENTS BY STUDENTS (Within & Outside State)
CREATE TABLE IF NOT EXISTS inst_inter_inst_awards (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  student_name     VARCHAR(190) NOT NULL,
  reg_no           VARCHAR(50)  NOT NULL,
  event_name       TEXT         NOT NULL,
  host_institution VARCHAR(255) NOT NULL,
  state_name       VARCHAR(100) NULL,
  location         VARCHAR(190) NOT NULL,
  award_medal      VARCHAR(190) NOT NULL,
  position_secured VARCHAR(100) NULL,
  event_date       VARCHAR(50)  NOT NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iia_dept (department),
  KEY idx_iia_status (status),
  KEY idx_iia_year (academic_year),
  KEY idx_iia_created (created_by),
  CONSTRAINT fk_iia_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iia_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 29. NO OF VALUE ADDED COURSE / HANDS ON TRAINING COURSES
CREATE TABLE IF NOT EXISTS inst_value_added_courses (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  academic_year       VARCHAR(20)  NOT NULL,
  department          VARCHAR(150) NOT NULL,
  exam_session        VARCHAR(50)  NULL,
  course_name         TEXT         NOT NULL,
  course_type         VARCHAR(100) NULL,
  organizer           VARCHAR(255) NOT NULL,
  start_date          VARCHAR(50)  NOT NULL,
  end_date            VARCHAR(50)  NOT NULL,
  duration            VARCHAR(100) NULL,
  participants        INT          NOT NULL DEFAULT 0,
  faculty_coordinator VARCHAR(190) NULL,
  description         TEXT         NULL,
  outcome             TEXT         NULL,
  proof_file          VARCHAR(255) NULL,
  status              ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark       VARCHAR(500) NULL,
  created_by          INT          NULL,
  approved_by         INT          NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ivac_dept (department),
  KEY idx_ivac_status (status),
  KEY idx_ivac_year (academic_year),
  KEY idx_ivac_created (created_by),
  CONSTRAINT fk_ivac_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ivac_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 30. EVENT PARTICIPATION IN SPORTS - STATE LEVEL
CREATE TABLE IF NOT EXISTS inst_sports_state (
  id                     INT AUTO_INCREMENT PRIMARY KEY,
  academic_year          VARCHAR(20)  NOT NULL,
  department             VARCHAR(150) NOT NULL,
  exam_session           VARCHAR(50)  NULL,
  student_name           VARCHAR(190) NOT NULL,
  reg_no                 VARCHAR(50)  NOT NULL,
  sport                  VARCHAR(100) NOT NULL,
  event_name             TEXT         NOT NULL,
  level_secured          VARCHAR(50)  NOT NULL DEFAULT 'State',
  event_date             VARCHAR(50)  NOT NULL,
  venue                  VARCHAR(255) NOT NULL,
  participation_position VARCHAR(190) NULL,
  award                  VARCHAR(190) NULL,
  proof_file             VARCHAR(255) NULL,
  status                 ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark          VARCHAR(500) NULL,
  created_by             INT          NULL,
  approved_by            INT          NULL,
  created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iss_dept (department),
  KEY idx_iss_status (status),
  KEY idx_iss_year (academic_year),
  KEY idx_iss_created (created_by),
  CONSTRAINT fk_iss_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iss_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 31. EVENT PARTICIPATION IN SPORTS - NATIONAL LEVEL
CREATE TABLE IF NOT EXISTS inst_sports_national (
  id                     INT AUTO_INCREMENT PRIMARY KEY,
  academic_year          VARCHAR(20)  NOT NULL,
  department             VARCHAR(150) NOT NULL,
  exam_session           VARCHAR(50)  NULL,
  student_name           VARCHAR(190) NOT NULL,
  reg_no                 VARCHAR(50)  NOT NULL,
  sport                  VARCHAR(100) NOT NULL,
  event_name             TEXT         NOT NULL,
  level_secured          VARCHAR(50)  NOT NULL DEFAULT 'National',
  event_date             VARCHAR(50)  NOT NULL,
  venue                  VARCHAR(255) NOT NULL,
  participation_position VARCHAR(190) NULL,
  award                  VARCHAR(190) NULL,
  proof_file             VARCHAR(255) NULL,
  status                 ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark          VARCHAR(500) NULL,
  created_by             INT          NULL,
  approved_by            INT          NULL,
  created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_isn_dept (department),
  KEY idx_isn_status (status),
  KEY idx_isn_year (academic_year),
  KEY idx_isn_created (created_by),
  CONSTRAINT fk_isn_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_isn_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 32. INNOVATION EVENTS NEED TO CONDUCT IN EVERY DEPARTMENT
CREATE TABLE IF NOT EXISTS inst_innovation_events (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  event_name       TEXT         NOT NULL,
  event_type       VARCHAR(100) NOT NULL,
  event_date       VARCHAR(50)  NOT NULL,
  coordinator      VARCHAR(190) NOT NULL,
  participants     INT          NOT NULL DEFAULT 0,
  outcome          TEXT         NULL,
  innovation_theme VARCHAR(255) NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iie_dept (department),
  KEY idx_iie_status (status),
  KEY idx_iie_year (academic_year),
  KEY idx_iie_created (created_by),
  CONSTRAINT fk_iie_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iie_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 33. IIC ACTIVITIES
CREATE TABLE IF NOT EXISTS inst_iic_activities (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  academic_year VARCHAR(20)  NOT NULL,
  department    VARCHAR(150) NOT NULL,
  exam_session  VARCHAR(50)  NULL,
  activity_name TEXT         NOT NULL,
  activity_type VARCHAR(100) NOT NULL,
  activity_date VARCHAR(50)  NOT NULL,
  organizer     VARCHAR(255) NOT NULL,
  coordinator   VARCHAR(190) NOT NULL,
  participants  INT          NOT NULL DEFAULT 0,
  outcome       TEXT         NULL,
  proof_file    VARCHAR(255) NULL,
  status        ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark VARCHAR(500) NULL,
  created_by    INT          NULL,
  approved_by   INT          NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iiic_dept (department),
  KEY idx_iiic_status (status),
  KEY idx_iiic_year (academic_year),
  KEY idx_iiic_created (created_by),
  CONSTRAINT fk_iiic_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iiic_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 34. WEBSITE UPDATION
CREATE TABLE IF NOT EXISTS inst_website_updations (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  academic_year VARCHAR(20)  NOT NULL,
  department   VARCHAR(150) NOT NULL,
  exam_session VARCHAR(50)  NULL,
  update_title VARCHAR(255) NOT NULL,
  page_section VARCHAR(255) NOT NULL,
  updated_by   VARCHAR(190) NOT NULL,
  update_date  VARCHAR(50)  NOT NULL,
  description  TEXT         NULL,
  site_url     VARCHAR(500) NULL,
  proof_file   VARCHAR(255) NULL,
  status       ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark VARCHAR(500) NULL,
  created_by   INT          NULL,
  approved_by  INT          NULL,
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iwu_dept (department),
  KEY idx_iwu_status (status),
  KEY idx_iwu_year (academic_year),
  KEY idx_iwu_created (created_by),
  CONSTRAINT fk_iwu_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iwu_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 35. GOOGLE RATING
CREATE TABLE IF NOT EXISTS inst_google_ratings (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  academic_year    VARCHAR(20)  NOT NULL,
  department       VARCHAR(150) NOT NULL,
  exam_session     VARCHAR(50)  NULL,
  google_rating    DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  review_count     INT          NOT NULL DEFAULT 0,
  measurement_date VARCHAR(50)  NOT NULL,
  remarks          TEXT         NULL,
  proof_file       VARCHAR(255) NULL,
  status           ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark    VARCHAR(500) NULL,
  created_by       INT          NULL,
  approved_by      INT          NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_igr_dept (department),
  KEY idx_igr_status (status),
  KEY idx_igr_year (academic_year),
  KEY idx_igr_created (created_by),
  CONSTRAINT fk_igr_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_igr_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 36. START UP
CREATE TABLE IF NOT EXISTS inst_startups (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  academic_year       VARCHAR(20)  NOT NULL,
  department          VARCHAR(150) NOT NULL,
  exam_session        VARCHAR(50)  NULL,
  startup_name        VARCHAR(255) NOT NULL,
  founders            TEXT         NOT NULL,
  founder_type        VARCHAR(50)  NOT NULL DEFAULT 'Student',
  reg_no              VARCHAR(50)  NULL,
  startup_type        VARCHAR(100) NULL,
  registration_number VARCHAR(100) NULL,
  registration_date   VARCHAR(50)  NULL,
  startup_status      VARCHAR(100) NULL,
  description         TEXT         NULL,
  proof_file          VARCHAR(255) NULL,
  status              ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark       VARCHAR(500) NULL,
  created_by          INT          NULL,
  approved_by         INT          NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_isup_dept (department),
  KEY idx_isup_status (status),
  KEY idx_isup_year (academic_year),
  KEY idx_isup_created (created_by),
  CONSTRAINT fk_isup_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_isup_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 37. ALUMNI CHAPTER
CREATE TABLE IF NOT EXISTS inst_alumni_chapters (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  academic_year  VARCHAR(20)  NOT NULL,
  department     VARCHAR(150) NOT NULL,
  exam_session   VARCHAR(50)  NULL,
  chapter_name   VARCHAR(255) NOT NULL,
  location       VARCHAR(190) NOT NULL,
  coordinator    VARCHAR(190) NOT NULL,
  formation_date VARCHAR(50)  NOT NULL,
  member_count   INT          NOT NULL DEFAULT 0,
  activities     TEXT         NULL,
  chapter_status VARCHAR(100) NULL,
  proof_file     VARCHAR(255) NULL,
  status         ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark  VARCHAR(500) NULL,
  created_by     INT          NULL,
  approved_by    INT          NULL,
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iac_dept (department),
  KEY idx_iac_status (status),
  KEY idx_iac_year (academic_year),
  KEY idx_iac_created (created_by),
  CONSTRAINT fk_iac_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iac_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 38. AWARDS & RECOGNITION (for DEPT/ FACULTY), BoS MEMBER, DC MEMBER, QP/KEY SETTING, etc.
CREATE TABLE IF NOT EXISTS inst_awards_recognitions (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  academic_year       VARCHAR(20)  NOT NULL,
  department          VARCHAR(150) NOT NULL,
  exam_session        VARCHAR(50)  NULL,
  faculty_name        VARCHAR(190) NULL,
  person_name         VARCHAR(190) NOT NULL,
  recognition_type    VARCHAR(100) NOT NULL,
  organization        VARCHAR(255) NOT NULL,
  title_award         TEXT         NOT NULL,
  achievement_date    VARCHAR(50)  NULL,
  role_responsibility TEXT         NULL,
  reference_number    VARCHAR(100) NULL,
  remarks             TEXT         NULL,
  proof_file          VARCHAR(255) NULL,
  status              ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark       VARCHAR(500) NULL,
  created_by          INT          NULL,
  approved_by         INT          NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_iar_dept (department),
  KEY idx_iar_status (status),
  KEY idx_iar_year (academic_year),
  KEY idx_iar_created (created_by),
  CONSTRAINT fk_iar_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_iar_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 39. NO. OF STUDENTS COMPLETED IIT-BOMBAY SPOKEN TUTORIAL COURSES
CREATE TABLE IF NOT EXISTS inst_spoken_tutorials (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  academic_year   VARCHAR(20)  NOT NULL,
  department      VARCHAR(150) NOT NULL,
  exam_session    VARCHAR(50)  NULL,
  student_name    VARCHAR(190) NOT NULL,
  reg_no          VARCHAR(50)  NOT NULL,
  course_name     VARCHAR(255) NOT NULL,
  tutorial_name   VARCHAR(255) NOT NULL,
  completion_date VARCHAR(50)  NOT NULL,
  certificate_id  VARCHAR(100) NULL,
  platform        VARCHAR(100) NOT NULL DEFAULT 'IIT-Bombay Spoken Tutorial',
  proof_file      VARCHAR(255) NULL,
  status          ENUM('Draft','Submitted','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  review_remark   VARCHAR(500) NULL,
  created_by      INT          NULL,
  approved_by     INT          NULL,
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_istut_dept (department),
  KEY idx_istut_status (status),
  KEY idx_istut_year (academic_year),
  KEY idx_istut_created (created_by),
  CONSTRAINT fk_istut_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_istut_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
